Add dependency checks

diff --git a/ebu-norm b/ebu-norm
--- a/ebu-norm
+++ b/ebu-norm
@@ -6,6 +6,21 @@
 # Option: 
 #  -t   Specify integrated loudness target, e.g. -t -20         
 
+# Check availability of dependencies
+function checkAvail()
+{
+	which "$1" >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "tool \"$1\" not found." >&2
+		exit 1
+	fi
+}
+
+for tool in {ebur128,sox,bc}; \
+	do checkAvail "$tool"; done
+
 
 # Select LUFS target based on -t flag or -23 LUFS default
 if [ $# -eq 0 ]
diff --git a/ebu-scan b/ebu-scan
--- a/ebu-scan
+++ b/ebu-scan
@@ -4,6 +4,21 @@
 
 # Usage: ebu-scan <input files>.                          
 
+# Check availability of dependencies
+function checkAvail()
+{
+	which "$1" >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "tool \"$1\" not found." >&2
+		exit 1
+	fi
+}
+
+for tool in {ebur128,sox,bc}; \
+	do checkAvail "$tool"; done
+
 if [ $# -eq 0 ]
 then
 	echo "Usage: ebu-scan <input files>"
diff --git a/loudmax-norm b/loudmax-norm
--- a/loudmax-norm
+++ b/loudmax-norm
@@ -9,6 +9,21 @@
 # Loudmax Output value (change to -1.2 or even -1.5 in case of true peak overage)     
 LMO=-1
 
+# Check availability of dependencies
+function checkAvail()
+{
+	which "$1" >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "tool \"$1\" not found." >&2
+		exit 1
+	fi
+}
+
+for tool in {ebur128,sox,bc,/usr/lib/ladspa/la_LoudMax64.so}; \
+	do checkAvail "$tool"; done
+
 # Select LUFS target based on -t flag or -23 LUFS default
 if [ $# -eq 0 ]
 then
diff --git a/lsp-norm b/lsp-norm
--- a/lsp-norm
+++ b/lsp-norm
@@ -9,6 +9,21 @@
 # LSP Limiter output value
 LSPO=-1
 
+# Check availability of dependencies
+function checkAvail()
+{
+	which "$1" >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "tool \"$1\" not found." >&2
+		exit 1
+	fi
+}
+
+for tool in {ebur128,sox,bc,/usr/lib/ladspa/lsp-plugins-ladspa.so}; \
+	do checkAvail "$tool"; done
+
 # LSP ladspa gain coefficient based on above LSPO value (do not change!)
 LSPGC=$(echo "pow(10,$LSPO/20)" | bc -l ~/.bcrc )
 
