ebu-plot: add dependency checks

diff --git a/ebu-plot b/ebu-plot
--- a/ebu-plot
+++ b/ebu-plot
@@ -14,6 +14,21 @@
 W=1280
 H=720
 
+# Check availability of dependencies
+function checkAvail()
+{
+	which "$1" >/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "tool \"$1\" not found." >&2
+		exit 1
+	fi
+}
+
+for tool in {pwsh,ffmpeg,gnuplot,/usr/local/bin/ebu-plot.psl}; \
+	do checkAvail "$tool"; done
+
 SKIPPED=0
 SKIPFILE=$(mktemp)
 
